### PR TITLE
[skip ci] Disable blank issues

### LINKED ISSUE #281: Hi
I just wanted to say hi to @Lucaskyy. :D

### PR DESCRIPTION
**Pull request by Elierrr**
# Description

Disables blank issues.

Fixes #281

# Checklist:

- [x] I have reviewed my code thoroughly.

### CODE REVIEW

**Comment by Lucaskyy** [comment]
Thanks :P That's what you get when showing your friends a repo 😅

**Comment by andreasdc** [comment]
> Thanks :P That's what you get when showing your friends a repo 😅

If instead of his issues would come useful patches it would be better 👯‍♀️

**Comment by LewUwU** [comment]
> > Thanks :P That's what you get when showing your friends a repo 😅
> 
> If instead of his issues would come useful patches it would be better 👯‍♀️

What's your problem man? He's helping the project by fixing issues alr

**Comment by CyberFlameGO** [comment]
IMHO this was a bad change, sometimes blank issues are better.

**Pull request merged**
