### PR TITLE
Use FastMath

### PR DESCRIPTION
**Pull request by ghost**
Originally from 44b3807e1fb903b83aabfbbcc0c9440953f1c5c3
Also updates fast-uuid to version 0.2.0

### CODE REVIEW

**Comment by andreasdc** [comment]
MathHelper is better by 40-100%, just checked

**Comment by andreasdc** [comment]
> you should pr it over then :)

maybe someday I will :)

**Comment by vocant** [comment]
did you know we're in 2021? jafama fastmath offers better performance only on old processors and java 1.6.

**Comment by Elierrr** [comment]
> did you know we're in 2021? jafama fastmath offers better performance only on old processors and java 1.6.

Doesn't make it worse than code from 2014.

**Pull request merged**
