### PR TITLE
Recode of EnumProtocol & Suppliers

### PR DESCRIPTION
**Pull request by Lucaskyy**
Optimizing packet sending and receiving by using suppliers instead of Reflection.
Also remapped EnumProtocol to get a better understanding of it.

Since my recode broke ProtocolLib's packet registry, I've added a shim for it.
One caveat is that we now have an extra map, so extra memory has to be allocated.
There's a config option for this, so if you don't have ProtocolLib, I recommend you disable this.

### CODE REVIEW

**Comment by andreasdc** [comment]
Fck Plib 🚀

**Comment by LewUwU** [comment]
> WIP, don't use. ProtocolLib not working at the moment, needs fixing.

Fixed in my pr, needs merge

**Comment by Lucaskyy** [comment]
> > WIP, don't use. ProtocolLib not working at the moment, needs fixing.
> 
> Fixed in my pr, needs merge

Hmm? I can't see a PR anywhere.

**Comment by LewUwU** [comment]
> > > WIP, don't use. ProtocolLib not working at the moment, needs fixing.
> > 
> > 
> > Fixed in my pr, needs merge
> 
> Hmm? I can't see a PR anywhere.

https://github.com/dmulloy2/ProtocolLib/pulls

**Comment by Lucaskyy** [comment]
Oh, I see. So the issue is Netty, not my code xP

**Comment by Lucaskyy** [comment]
Not mergeable yet, currently debugging an issue causing the EnumProtocol attribute to be null.

**Comment by Lucaskyy** [comment]
Some little benchmarks. My PC is not that good (Intel i5) and I have a shit ton of programs open, so these can make the benchmarks worse.

Before:
Before Img

After:
After Img

**Comment by Lucaskyy** [comment]
ProtocolLib is still not working, it seems that I'll have to create a shim for it.

**Comment by Lucaskyy** [comment]
This PR is finished. If people have the time, please review this PR so I can fix any mistakes I might've made. :)

**Review by Elierrr — APPROVED** [review]
LGTM!

**Comment by hpfxd** [comment]
Here are my results from testing this.
- 150 bots, jumping around a superflat world in a 64x64 area.
- Mostly default configuration, except for encryption being disabled.
- aarch64 machine, 4GB memory allocated
  - I also tested this on my personal machine (Ryzen 5 5600x, 20 GB memory allocated), but profiling accurately on Windows is challenging, although results were consistent with the shown results.

**Entity tracking**
| Baseline | This PR |
| -------- | ------- |
| img | img |

**Netty event group**
| Baseline | This PR |
| -------- | ------- |
| img | img |

As seen, this PR seems to improve performance slightly during packet sending.

I have concerns about plugin compatibility, due to field renaming and removal.  
I see you've already merged this, but please test it with the following plugins & libraries if you have time:
- [ViaVersion](https://github.com/ViaVersion/ViaVersion)
- [TinyProtocol](https://github.com/dmulloy2/ProtocolLib/blob/master/TinyProtocol/src/main/java/com/comphenix/tinyprotocol/TinyProtocol.java)
- [packetevents](https://github.com/retrooper/packetevents)

**Comment by Lucaskyy** [comment]
@hpfxd I've tested it with ViaVersion, no issues.
ProtocolLib had issues (due to not using BiMap anymore), so I created a shim for it (read-only).
I'll test the other plugins too.

**Comment by Lucaskyy** [comment]
As for testing packetevents, I'll also put Vulcan on it to see it in action (better testing)

**Comment by Lucaskyy** [comment]
@hpfxd Sorry, took a bit longer than expected.
Just installing PacketEvents works, don't get any errors or whatever.
ProtocolLib works just fine too, and so does ViaVersion.

**Comment by andreasdc** [comment]
image

**Comment by Lucaskyy** [comment]
@andreasdc I'm not sure if something said bye-bye on your computer, but it definitely shouldn't be slower than Reflection.

**Comment by andreasdc** [comment]
> @andreasdc I'm not sure if something said bye-bye on your computer, but it definitely shouldn't be slower than Reflection.

What do you mean by that? It's profiler from production.

**Comment by Lucaskyy** [comment]
Also, @hpfxd I tested using ThotPatrol (another AC) which uses ProtocolLib instead of PacketEvents, and that worked fine.
So I think this PR should work just fine, but if any issues occur I'll fix them.

**Comment by Lucaskyy** [comment]
> > @andreasdc I'm not sure if something said bye-bye on your computer, but it definitely shouldn't be slower than Reflection.
> 
> What do you mean by that? It's profiler from production.

I don't trust that profiler report at all, since there's no way that suppliers would be slower than Reflection. :P

**Comment by andreasdc** [comment]
> > > @andreasdc I'm not sure if something said bye-bye on your computer, but it definitely shouldn't be slower than Reflection.
> > 
> > 
> > What do you mean by that? It's profiler from production.
> 
> I don't trust that profiler report at all, since there's no way that suppliers would be slower than Reflection. :P
> 
> Or, in other words, I'm very confused that this would be slower.
> 
> Could you instead do the same as hpfxd, and try the latest production build and a couple of builds earlier before this was added? Since you can't guarantee that you will get the same results on another day.

You had earlier profiler and current, I will make sure it has the newest changes tomorrow, maybe there was a little more players too.

**Comment by andreasdc** [comment]
@Lucaskyy 
image

**Pull request merged**
