### PR TITLE
Directly rename methods instead of using OBFHELPERs and reobfuscate them

### LINKED ISSUE #301: Crash when tryinmg to use protocol support for servers running minecraft 1.8
### Observed Behavior

The server crashes with this error messange:

`java.lang.ExceptionInInitializerError
[18:52:50 WARN]:     at protocolsupport.ProtocolSupport.onLoad(ProtocolSupport.java:24)
[18:52:50 WARN]:     at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(CraftServer.java:329)
[18:52:50 WARN]:     at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:207)
[18:52:50 WARN]:     at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:562)
[18:52:50 WARN]:     at java.lang.Thread.run(Thread.java:748)
[18:52:50 WARN]: Caused by: java.lang.NoSuchFieldException: h
[18:52:50 WARN]:     at java.lang.Class.getDeclaredField(Class.java:2070)
[18:52:50 WARN]:     at protocolsupport.protocol.ServerBoundPacket.<init>(ServerBoundPacket.java:84)
[18:52:50 WARN]:     at protocolsupport.protocol.ServerBoundPacket.<clinit>(ServerBoundPacket.java:45)
[18:52:50 WARN]:     ... 5 more`

more info in the log file:

[latest.log](https://github.com/CobbleSword/NachoSpigot/files/7729562/latest.log)
 

### Expected Behavior

The server should have started as usual and protocol support should be working. It worked with the og taco spigot for 1.8.8 and with the latest spigot 1.8.8 builds version that features fixes for log4j.

### Steps To Reproduce

Make a test server using java 8 on a macOS intel host (tested on big sur and high sierra, should be reproduceable with linux), then use protocollib + protocol support for server running 1.8.8 (https://protocol.support/old/).

### Plugin List

 TimTheEnchanter, Essentials, EssentialsProtect, EssentialsChat, GroupManager, ClearLag, EssentialsAntiBuild, iConomy, DisableCommands, Chairs, LagMonitor, Lockette, Vault, EssentialsSpawn, ProtocolSupport, Multiverse-Core, ProtocolLib, Citizens, SkinsRestorer, Factions, ChestShop, AuthMe, ClientStats.

### Server Version

Latest commit dec. 16th 2021.

### Other

_No response_

### Agreements

- [X] You were able to find this issue on the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this bug.
- [X] You have confirmed that you are NOT using a fork of NachoSpigot in any way. **YOUR changes are not OUR faults.**

### PR DESCRIPTION
**Pull request by Elierrr**
Completely reobfuscates all OBFHELPERs and obfuscates ProtocolLib's shim to work with ProtocolSupport using SpecialSource

Fixes #301 

# Additional comments

This uses SpecialSource's maven plugin to reobfuscate all OBFHELPERs.

### CODE REVIEW

**Comment by Lucaskyy** [comment]
Thanks for this PR! Have you tested this to make sure the server compiles and runs correctly? :)

**Comment by Elierrr** [comment]
Tested and works fine, I'm currently comparing the decompiled NachoSpigot and decompiled version of this PR to make sure I didn't miss any OBFHELPERs that I didn't add to `reobf-mappings.csrg`.

**Comment by Elierrr** [comment]
Good to go, once this compiles you can merge this! @Lucaskyy

**Comment by Lucaskyy** [comment]
Thanks for this PR! :)

**Pull request merged**
