### PR TITLE
bump netty to 4.1.75

### PR DESCRIPTION
**Pull request by crafter23456**
# Description

Bumped the netty version to latest (4.7.0) & adjust the protocollib check.

# Additional Comments

Merge this PR if you think its ready to move on. The switch to protocollib 4.7.0 to 4.8.0 doesnt need that much time and doesnt change things so everybody can simply upgrade.

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by LewUwU** [comment]
Not recommended to merge right now, we should wait the situation to be stable (ProtocolLib, PacketEvents, etc)

**Comment by Lucaskyy** [comment]
Converted this to a draft until it is safe to merge.

**Comment by CyberFlameGO** [comment]
iirc every time we've tried to update netty, it's caused issues 💀

**Comment by crafter23456** [comment]
It was everytime the problem because of people which use an old version. Now is Protocollib 4.8.0 on spigot and 5.0.0 (thanks klaro) as snapshot, both work well with netty 4.1.74. So we can wait a bit until the majority moves on and then command them to update. I mean it's only a drag and drop replacement and nothing else

**Comment by LewUwU** [comment]
I think it's time to merge this

**Review by hpfxd — APPROVED** [review]

**Pull request closed without merging**
