### PR TITLE
Migrate to YAML configuration

### PR DESCRIPTION
**Pull request by Elierrr**
Adds support for categories, comments, and world-specific configurations.

- [x] Add YAML file
- [x] Move all configuration options
- [x] Add migration from nacho.json
- [x] Add categories
- [x] Add comments
- [x] Move some configurations to world config

### CODE REVIEW

**Comment by CyberFlameGO** [comment]
Ehhhhh, if you're gonna move to a more human-friendly configuration format I'd recommend TOML, but this is alright

**Comment by Lucaskyy** [comment]
Awesome, thank you for this PR! I'll merge it when it's ready. Also, yes TOML is more human readable, but YAML is better in this case for consistency.

**Comment by Elierrr** [comment]
@Lucaskyy

**Review by Lucaskyy — APPROVED** [review]
Thank you so much for this PR :) Looks all good to me!

**Pull request merged**
