### PR TITLE
Fix deleting nacho.json during migration

### LINKED ISSUE #218: Compile issues
Actually, from last yaml config patch, it won't compile, and isn't only me.

### PR DESCRIPTION
**Pull request by Elierrr**
Closes #218

### CODE REVIEW

**Review by sadcenter — APPROVED** [review]
fixes the problem

**Comment by Lucaskyy** [comment]
Seems like there's a conflict. Could you fix it? If not, I'll try to fix it myself later.

**Comment by Elierrr** [comment]
@Lucaskyy

**Comment by Lucaskyy** [comment]
Thank you!

**Pull request merged**
