### PR TITLE
Remove FastMath sin and cos config

### LINKED ISSUE #244: Fastmath breaks projectiles
Setting `enable-fastmath-cos-sin` to `true` causes projectiles such as bows, eggs and enderpearls to fly into wrong directions when shooting them in north or east direction.

### PR DESCRIPTION
**Pull request by Elierrr**
# Description

This PR removes FastMath's con and sin methods. This is done due to the fact that FastMath's con and sin gives [less performance and inaccurate results](https://github.com/CobbleSword/NachoSpigot/files/7550597/fastmathvsvanilla.txt). 

Fixes #244 

# How has this been tested?

I have tested #244.

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by refractored** [comment]
perhaps add a comment that says it degrades performance instead?

**Comment by Elierrr** [comment]
> perhaps add a comment that says it degrades performance instead?

There's no point in even having it if all it does is cause issues and decrease performance.

**Comment by refractored** [comment]
makes sense

**Comment by Lucaskyy** [comment]
I agree with this. Until this shows that it's worth keeping, I'll remove it.
Thanks Elierrr!

**Pull request merged**
