### PR TITLE
Ender Pearl Spawn Patch

### PR DESCRIPTION
**Pull request by Tofpu**
# Description

Please provide a detailed description of the changes you have made.

- When attempted to spawn an Ender Pearl with the ``World#spawnEntity`` method, it throwed an ``NullPointerException`` exception. I solved it by adding a few null checks to the EntityProjectile class and sat the position rotation parameters to 0 when said entity is null (though it'd be better than ignoring it entirely)
- Removed two imports that prevented the server jar from compiling properly (FIXED IN #272)

# How has this been tested?

How have you tested the changes you have made?
- By re-attempting to spawn the Ender Pearl with the mentioned method

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Elierrr — APPROVED** [review]
Can someone test if this also fixes #267?

**Comment by Tofpu** [comment]
I checked and it does not unfortunately. do you want me to include the fix here?

**Comment by Elierrr** [comment]
> Awaiting for permission to push the changes here (although I'd feel like a separate pr would be suited better, up to you)

It would probably be better to put in another PR. I'll test both when I can.

**Comment by Lucaskyy** [comment]
@Tofpu A separate PR would be better yes :)

**Comment by Tofpu** [comment]
> @Tofpu A separate PR would be better yes :)
> > Awaiting for permission to push the changes here (although I'd feel like a separate pr would be suited better, up to you)
> 
> It would probably be better to put in another PR. I'll test both when I can.

Got it! You can view the PR at #273

**Comment by Elierrr** [comment]
Tested and works as expected!﻿

**Comment by Lucaskyy** [comment]
Thanks, Tofpu for this PR! :)

**Pull request merged**
