### PR TITLE
Update Guava and GSON

### LINKED ISSUE #322: Update guava to latest
### Describe the feature

Update all google libraries to it's latest version, currently guava 31.0.1 and gson 2.8.9 to achieve higher security, allow plugins to use new libary features and better performance.

### Technical implementation

Update dependencies in pom.yml and fix compilation errors in
- CraftServer
- BaseBlockPosotion
- BlockStateList
- BlockState
- PacketPlayOUtPlayerInfo
- TripwireHook
- and EntitySlice

### Other

This might break compatibility with rare plugins that deeply interact with nms.
This should be properly tested before publishing to the official Nacho builds.

### Agreements

- [X] You have confirmed that this feature does not yet exist in the latest version of NachoSpigot.
- [X] You have confirmed that there aren’t any issues open regarding this feature.

### PR DESCRIPTION
**Pull request by Elierrr**
Updates guava and gson to the latest versions

Closes #322

## Todo List:

- [x] Fix CraftServer
- [x] Fix compile errors in NMS
- [x] Import other NMS classes with errors and fix them
- [x] Shade an older version of guava’s Objects for plugins
- [x] Re-add MoreExecutors.sameThreadExecutor

### CODE REVIEW

**Comment by Dysaido** [comment]
If you want to upgrade the guava, when the worldguard crashes, because it can't find some import from guava.

**Comment by LewUwU** [comment]
Like @Dysaido said, if you wan't to update guava you should fix the compatibilities issues with plugins like WG

**Comment by Sneakometer** [comment]
Can confirm this works like a charm with
- NoCheatPlus
- CloudNet Bridge
- ViaVersion
- Multiverse Core
- Luckperms
- WorldEdit
- Plotme/squared
- All of our custom plugins
right out of the box.

Great job!

**Comment by LewUwU** [comment]
> Can confirm this works like a charm with
> 
> * NoCheatPlus
> * CloudNet Bridge
> * ViaVersion
> * Multiverse Core
> * Luckperms
> * WorldEdit
> * Plotme/squared
> * ArmorStandTools
> * IllegalStack
> * DecoHeads
> * All of our custom plugins
> 
> right out of the box.
> 
> Great job!
> 
> Edit: I see the GuavaInjector is failing on jre 17. Maybe also add a toggle for this in config? Thanks!

Can you send the error of GuavaInjector on Java 17?

**Comment by Elierrr** [comment]
> > Can confirm this works like a charm with
> > 
> > * NoCheatPlus
> > * CloudNet Bridge
> > * ViaVersion
> > * Multiverse Core
> > * Luckperms
> > * WorldEdit
> > * Plotme/squared
> > * ArmorStandTools
> > * IllegalStack
> > * DecoHeads
> > * All of our custom plugins
> > 
> > right out of the box.
> > Great job!
> > Edit: I see the GuavaInjector is failing on jre 17. Maybe also add a toggle for this in config? Thanks!
> 
> Can you send the error of GuavaInjector on Java 17?

It’s the same as #211

**Comment by Sneakometer** [comment]
> > Can confirm this works like a charm with
> > 
> > * NoCheatPlus
> > * CloudNet Bridge
> > * ViaVersion
> > * Multiverse Core
> > * Luckperms
> > * WorldEdit
> > * Plotme/squared
> > * ArmorStandTools
> > * IllegalStack
> > * DecoHeads
> > * All of our custom plugins
> > 
> > right out of the box.
> > Great job!
> > Edit: I see the GuavaInjector is failing on jre 17. Maybe also add a toggle for this in config? Thanks!
> 
> Can you send the error of GuavaInjector on Java 17?

In case it's still needed:
```
[18:21:50] [Server thread/ERROR]: Exception while defining class
java.lang.reflect.InaccessibleObjectException: Unable to make protected final java.lang.Class java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int) throws java.lang.ClassFormatError accessible: module java.base does not "opens java.lang" to unnamed module @3cb1ffe6
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:354) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:297) ~[?:?]
	at java.lang.reflect.Method.checkCanSetAccessible(Method.java:199) ~[?:?]
	at java.lang.reflect.Method.setAccessible(Method.java:193) ~[?:?]
	at dev.cobblesword.nachospigot.GuavaInjector.defineClass(GuavaInjector.java:20) [paper.jar:git-NachoSpigot-f03ddd8]
	at dev.cobblesword.nachospigot.GuavaInjector.<clinit>(GuavaInjector.java:37) [paper.jar:git-NachoSpigot-f03ddd8]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:209) [paper.jar:git-NachoSpigot-f03ddd8]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:559) [paper.jar:git-NachoSpigot-f03ddd8]
	at java.lang.Thread.run(Thread.java:833) [?:?]
```

**Comment by Lucaskyy** [comment]
Thanks a lot @Elierrr for this PR! Sadly I do not have the time to test this to be sure, but I guess it should be fine. :)

**Pull request merged**
