### PR TITLE
Fix the tnt issue. blocks were not breaking

### PR DESCRIPTION
**Pull request by Sasuke449**
# Description

Please provide a detailed description of the changes you have made.
removed a check from explosions

Fixes/Adds # (issue)
fixes issue #302 

# How has this been tested?
I got the issue reporter to test this. 

How have you tested the changes you have made?
yep

# Additional Comments

Provide any additional information regarding this pull request.
this pr should fix the issue for explosions not breaking blocks

### CODE REVIEW

**Review by Elierrr — APPROVED** [review]

**Review by xzolw — APPROVED** [review]

**Comment by LewUwU** [comment]
Why we can't just drop the Ion patch completely? since is broken

**Review by LewUwU — APPROVED** [review]

**Comment by Sasuke449** [comment]
> Why we can't just drop the Ion patch completely? since is broken

its not needed tbh. because i have fixed the blocks issue and there is no further issue with lon spigot patch until now lol

**Comment by Elierrr** [comment]
> > Why we can't just drop the Ion patch completely? since is broken
> 
> its not needed tbh. because i have fixed the blocks issue and there is no further issue with lon spigot patch until now lol

The IonSpigot patch also causes #230

**Comment by Sasuke449** [comment]
> > > Why we can't just drop the Ion patch completely? since is broken
> > 
> > 
> > its not needed tbh. because i have fixed the blocks issue and there is no further issue with lon spigot patch until now lol
> 
> The IonSpigot patch also causes #230

a pr containing fix is already merged right? (https://github.com/CobbleSword/NachoSpigot/pull/234)

**Comment by Elierrr** [comment]
That fix was completely broke explosions and was reverted in #268

**Comment by Lucaskyy** [comment]
Thanks for the PR, but #276 supersedes this. So I'm going to close this one in favor of #276 
Thanks anyway!

**Pull request closed without merging**
