### PR TITLE
Convert to WeakReference

### PR DESCRIPTION
**Pull request by Elierrr**
https://github.com/CobbleSword/NachoSpigot/commit/154536b0dfb042a74de4bf01ee08f86038d7e091#r54674930

### CODE REVIEW

**Comment by LewUwU** [comment]
And here is another NullPointerException,

Change 'return lastDamageEvent.get();' to 'return this.lastDamageEvent == null ? null : this.lastDamageEvent.get();'

**Comment by Elierrr** [comment]
> And here is another NullPointerException,
> 
> Change 'return lastDamageEvent.get();' to 'return this.lastDamageEvent == null ? null : this.lastDamageEvent.get();'

Fixed

**Review by LewUwU — APPROVED** [review]

**Comment by LewUwU** [comment]
LGTM, no breaking api changes since the lastDamageEvent field is private and the WeakReference is used on the set and get methods, can be merged.

**Review by CyberFlameGO — APPROVED** [review]
Agreed, this is a useful change. @Lucaskyy, @hpfxd or @HeathLoganCampbell please merge :)

**Comment by Lucaskyy** [comment]
Finally. Wasn't able to merge this 3 days ago due to a GitHub issue. Thanks!

**Pull request merged**
