### PR TITLE
Fix #204

### LINKED ISSUE #204: Cancelling block place events passes physics update
Placed redstone wire interacts with redstone torches, even when block place is cancelled.

### PR DESCRIPTION
**Pull request by LewUwU**
# Description

Please provide a detailed description of the changes you have made.

Fixes/Adds # (issue)

# How has this been tested?

How have you tested the changes you have made?

# Additional Comments

Provide any additional information regarding this pull request.

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by andreasdc** [comment]
I already have this in my code.

**Comment by LewUwU** [comment]
> I already have this in my code.

Then you broke something

**Review by Elierrr — APPROVED** [review]

**Comment by andreasdc** [comment]
> > I already have this in my code.
> 
> Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled

I doubt so, probably, but you can test it by yourself.

**Comment by andreasdc** [comment]
> > I already have this in my code.
> 
> Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled

Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.

**Review by xzolw — APPROVED** [review]

**Comment by LewUwU** [comment]
> > > I already have this in my code.
> > 
> > 
> > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> 
> Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.

Based on your logic, redstone dust isn't a block?

**Comment by Lucaskyy** [comment]
Thank you for this PR! :)

**Comment by andreasdc** [comment]
> > > > I already have this in my code.
> > > 
> > > 
> > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > 
> > 
> > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> 
> Based on your logic, redstone dust isn't a block?

Test and then say something.

**Comment by LewUwU** [comment]
> > > > > I already have this in my code.
> > > > 
> > > > 
> > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > > 
> > > 
> > > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > 
> > 
> > Based on your logic, redstone dust isn't a block?
> 
> Test and then say something. Simple debug when placing redstone dust.

Do it yourself

Your issue was titled with block place event cancelled calls a physics update, i fixed it.

**Comment by andreasdc** [comment]
> .

When placing redstone dust.

**Comment by andreasdc** [comment]
> > > I already have this in my code.
> > 
> > 
> > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> 
> Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.

I already did it.

**Comment by LewUwU** [comment]
> > > > I already have this in my code.
> > > 
> > > 
> > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > 
> > 
> > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> 
> I already did it.

Then fix your own issue since you already did a debug stage, i already fixed the titled issue

**Comment by andreasdc** [comment]
> > > > > I already have this in my code.
> > > > 
> > > > 
> > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > > 
> > > 
> > > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > 
> > 
> > I already did it.
> 
> Then fix your own issue since you already did a debug stage, i already fixed the titled issue

Titled, but not described. Don't mark it as a fix for the issue then.

**Comment by LewUwU** [comment]
> > > > > > I already have this in my code.
> > > > > 
> > > > > 
> > > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > > > 
> > > > 
> > > > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > > 
> > > 
> > > I already did it.
> > 
> > 
> > Then fix your own issue since you already did a debug stage, i already fixed the titled issue
> 
> Titled, but not described. Don't mark it as a fix for the issue then.

Your plugin is wrong made because you need to cancel the BlockRedstoneEvent, i fixed your titled issue, if you do strange things in a plugin or your fork is not my problem

**Comment by andreasdc** [comment]
> > > > > > > I already have this in my code.
> > > > > > 
> > > > > > 
> > > > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > > > > 
> > > > > 
> > > > > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > > > 
> > > > 
> > > > I already did it.
> > > 
> > > 
> > > Then fix your own issue since you already did a debug stage, i already fixed the titled issue
> > 
> > 
> > Titled, but not described. Don't mark it as a fix for the issue then.
> 
> Your plugin is wrong made because you need to cancel the BlockRedstoneEvent, i fixed your titled issue, if you do strange things in a plugin or your fork is not my problem

Shouldn't cancelled BlockPlaceEvent stop BlockRedstoneEvent?

**Comment by LewUwU** [comment]
> > > > > > > > I already have this in my code.
> > > > > > > 
> > > > > > > 
> > > > > > > Then you broke something because this patch prevents the physics update when BlockPlaceEvent is cancelled
> > > > > > 
> > > > > > 
> > > > > > Placing blocks - yes, placing redstone dust - not. Probably something with PandaRedstoneWire.
> > > > > 
> > > > > 
> > > > > I already did it.
> > > > 
> > > > 
> > > > Then fix your own issue since you already did a debug stage, i already fixed the titled issue
> > > 
> > > 
> > > Titled, but not described. Don't mark it as a fix for the issue then.
> > 
> > 
> > Your plugin is wrong made because you need to cancel the BlockRedstoneEvent, i fixed your titled issue, if you do strange things in a plugin or your fork is not my problem
> 
> Shouldn't cancelled BlockPlaceEvent stop BlockRedstoneEvent?

Why a event should cancel another event

**Comment by andreasdc** [comment]
> 

Why would you pass it to redstone even when block place is cancelled?

**Comment by LewUwU** [comment]
> > 
> 
> Why would you pass it to redstone even when block place is cancelled?

Ask to Mojang & CraftBukkit

**Comment by andreasdc** [comment]
> t

Here we are on NachoSpigot, already correcting Mojang & CraftBukkit's code.

**Comment by Lucaskyy** [comment]
Remind you; this is vanilla behavior! So even if we changed this, this could break plugins!

**Comment by andreasdc** [comment]
*sad violin music*

**Comment by andreasdc** [comment]
> Remind you; this is vanilla behavior! So even if we changed this, this could break plugins!

But plugin based on broken behaviour right? 🥇

**Pull request merged**
