### PR TITLE
Nacho-0052 Kick player who executes a creative action not in creative

### PR DESCRIPTION
**Pull request by HeathLoganCampbell**

### CODE REVIEW

**Comment by Lucaskyy** [comment]
LGTM, will check this soon.

**Review by LewUwU — CHANGES_REQUESTED** [review]
Do a config option to enable this

**Comment by HeathLoganCampbell** [comment]
Sure thing

**Comment by Outfluencer** [comment]
You could make the event cancellable and only kick the player if the event is not canceled

**Review by CyberFlameGO — APPROVED** [review]
LGTM

**Comment by Lucaskyy** [comment]
> You could make the event cancellable and only kick the player if the event is not canceled

Is there any use-case for that?

**Pull request merged**
