### PR TITLE
some changes

### PR DESCRIPTION
**Pull request by Lucaskyy**

### CODE REVIEW

**Comment by Lucaskyy** [comment]
Could anyone review and check if everything is all good to go?

**Comment by Lucaskyy** [comment]
Tested & working. Async issue is now fixed.
Spark report: https://spark.lucko.me/0prFCcaX6b

**Review by Elierrr — APPROVED** [review]
LGTM

**Comment by Rastrian** [comment]
LGTM!

**Review by xzolw — APPROVED** [review]

**Review by Rastrian — APPROVED** [review]

**Comment by Lucaskyy** [comment]
Sweet 👍 Merging!

**Pull request merged**
