### PR TITLE
Update ViaVersion Packages

### PR DESCRIPTION
**Pull request by RealBauHD**
The packages have been changed in the latest ViaVersion version.

### CODE REVIEW

**Comment by Outfluencer** [comment]
thats right needs to be merged

**Comment by Lucaskyy** [comment]
This won't work though for people using older versions of ViaVersion. Try checking first if the class exists, and then decide which class prefix to use.

**Review by CyberFlameGO — APPROVED** [review]
LGTM - adding a check for older versions would be beneficial though

**Comment by Lucaskyy** [comment]
Oh? Why close it?

**Comment by crafter23456** [comment]
> Oh? Why close it?

It got implemented in another PR #70

**Pull request closed without merging**
