### PR TITLE
Actually fix logger issues

### PR DESCRIPTION
**Pull request by Sneakometer**
Add proper log4j-slf4j18-impl aswell as slf4j api to fix compatibility problems with Luckperms & other plugins.
Fixes https://github.com/CobbleSword/NachoSpigot/issues/285
Tested with a bunch of plugins, including latest Luckperms.

# Checklist:

- [X] I have reviewed my code thoroughly.
- [X] I have tested my code.
- [X] My changes generate no new warnings

### CODE REVIEW

**Comment by Elierrr** [comment]
Wouldn't it be better to just use #284 and revert https://github.com/CobbleSword/NachoSpigot/commit/5e428c973f4083a06dc519d5d9568597f592794

**Comment by Sneakometer** [comment]
> Reference in new

Well, being stuck with outdated dependencies should be avoided if you ask me.

**Comment by Elierrr** [comment]
That makes sense.

**Review by Elierrr — APPROVED** [review]

**Comment by Lucaskyy** [comment]
Thanks for fixing it!

**Pull request merged**
