### PR TITLE
Update netty to 4.1.75.Final w/ support for ProtocolLib 4.7.0

### PR DESCRIPTION
**Pull request by Elierrr**
# Description

Updates netty to 4.1.75 with an additional fallback for plugins that use the netty-common artifact to get the netty version

Supersedes #374
Closes #374 

# How has this been tested?

Tested with ProtocolLib 4.7.0 and 4.8.0

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

@Lucaskyy

### CODE REVIEW

**Comment by crafter23456** [comment]
what did changed to support protocollib 4.7.0? can the maven resource plugin see which plugins doesnt work with that specific netty version? xd
besides of that, is it really that smart to get always the latest netty of the upcoming 5.0.0 version which refactors all packages and variables?

**Comment by Elierrr** [comment]
> what did changed to support protocollib 4.7.0? can the maven resource plugin see which plugins doesnt work with that specific netty version? xd besides of that, is it really that smart to get always the latest netty of the upcoming 5.0.0 version which refactors all packages and variables?

ProtocolLib uses netty's Version class to get the version of netty, which grabs the version from `io.netty.version.properties` using the artifact. ProtocolLib 4.7.0 grabs the version from the artifact `netty-common`, while 4.8.0+ grab it from `netty-all`. Also what do you mean from the latest of the upcoming 5.0.0? This is still using 4.1, not 5.0

**Comment by crafter23456** [comment]
> ProtocolLib uses netty's Version class to get the version of netty, which grabs the version from io.netty.version.properties using the artifact. ProtocolLib 4.7.0 grabs the version from the artifact netty-common, while 4.8.0+ grab it from netty-all.

ah okay 👍 

> Also what do you mean from the latest of the upcoming 5.0.0? This is still using 4.1, not 5.0

oof i read it wrong, i thought it catches the latest one :D 

do we still need the check for protocollib 4.6 or is that also superseeded by the catching of netty-common?

**Comment by Elierrr** [comment]
> do we still need the check for protocollib 4.6 or is that also superseeded by the catching of netty-common?

Yeah, we still need the check.

**Review by crafter23456 — APPROVED** [review]

**Review by LewUwU — APPROVED** [review]

**Comment by Lucaskyy** [comment]
Thank you!

**Pull request merged**
